//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Code_BreakersEventBudget
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListItem
    {
        public int ListID { get; set; }
        public int ListItemID { get; set; }
        public string ProductName { get; set; }
        public decimal Price { get; set; }
        public string GiftFor { get; set; }
        public int UserID { get; set; }
        public string ThumbnailUrl { get; set; }
    
        public virtual List List { get; set; }
        public virtual PersonalInfo PersonalInfo { get; set; }
    }
}
